exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/tarunsachdeva/blog"
  
title: Tarun Sachdeva
description: 

baseurl: "/blog"
production_url : http://tarunsachdeva.com/blog
BASE_PATH : http://tarunsachdeva.com/blog
permalink: /:year/:month/:day/:title:output_ext
date_format: "%b %-d, %Y"
